### ISSUE TITLE
Use TravisCI, CircleCI, GitlabCI, etc for checking PRs

### ISSUE THREAD

**Issue by nnadeau** [davidnsousa/mcsd#14]
### Feature request

- Tests should be run by a CI service for every commit/PR
- Only passing PRs should be merged

**Comment by davidnsousa** [comment]
@nnadeau is this an obligate requirement for JOSS? The automated tests that I have created as required by JOSS can be run with the MATLAB tool `runtests`. And this is done manually every time before a new commit. But as far as I know this (MATALAB tests) cannot be done automatically in the cloud with these TravisCL-like tools.

**Comment by davidnsousa** [comment]
@nnadeau I found how to do this :)
